project:
  type: website
  output-dir: docs

website:
  title: "My Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - addingp1.qmd
      - spring2024courses.qmd

format:
  html:
    theme: cosmo
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    css: styles.css
    toc: true

editor: visual

