project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - spring2024courses.qmd
format:
  html:
    theme: Sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#757879"
    linkcolor: "#ff33f0"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

